# Generated by Django 4.2.7 on 2023-12-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('dt', models.DateTimeField(verbose_name='Дата и время')),
                ('category', models.CharField(choices=[('SPORTS', 'Спорт'), ('IT', 'IT'), ('ANIMALS', 'Животные'), ('OTHER', 'Другое')], default='IT', max_length=64, verbose_name='Категория')),
            ],
        ),
    ]
